version: '3.7'

services:
  flask:
    build: ./flask
    ports:
      - "5000:5000"
    volumes:
      - ./flask/:/usr/src/flask/
    depends_on:
      - db
    command: >
      env FLASK_APP=app.py flask run --host=0.0.0.0 --port=5000

  db:
    image: postgres:12.0-alpine
    restart: always
    volumes:
      - dbvolume:/var/lib/postgresql/data/
    env_file:
      - ./.env.db

  nginx:
    image: nginx:1.17-alpine
    depends_on:
      - db
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"

volumes:
  dbvolume: